modLoader="javafml"
loaderVersion="[45,)"
license="Apache License version 2.0"

[[mods]]
modId="steal_dogs"
version="1.0.0"
displayName="steal_dogs"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="uaio"

[[dependencies.steal_dogs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




